### ISSUE TITLE
TODO: Implement filtering with the two favorites genres \ decades

### ISSUE THREAD

**Issue by miglrodri** [miglrodri/MusicFox_Web#4]
Em vez de filtrar por 1 genre e 1 decade,
filtrar por 2 genres ou 2 decades.

**Comment by miglrodri** [comment]
@luisj123 , isto está feito ne?

**Comment by miglrodri** [comment]
estive a testar e descobri bug, mas para já não consegui corrigir.
basicamente se limpares o cookie, e meteres 1 género no cookie, tipo rock:1.
e depois meteres outro género tipo: electronica:1

ele não guarda os dois nos favoritos.
guarda o rock primeiro, depois na segunda vez vai guardar o electronica por cima do rock.

meti a consola a imprimir os generos favoritos e as queries dos recommended. dá para ver que ele não mete os dois como favoritos nessa situação e a query vai com um dos regex vazios.

**Comment by luisj123** [comment]
Penso que agora já esta! menos um
